#-------------------------------
# General Site Settings
title: Yongjun He
logo-eth: logo-eth.png # You can add own logo.
logo-sfu: logo-sfu.svg
logo-nju: logo-nju.png
description:


#-------------------------------
# Author Settings
author:
  name: Yongjun He
  image: YongjunHe.jpg
  say-hello: Hello, I’m <strong>Yongjun He</strong>
  bio: I am a 3rd year PhD student in Computer Science at ETH Zurich, under the supervision of Prof. Dr. [Gustavo Alonso](https://systems.ethz.ch/people/profile.gustavo-alonso.html), Prof. [Ce Zhang](https://zhangce.github.io/), and Dr. [Theodoros Rekatsinas](https://thodrek.github.io/). 
       I am a member of the [Systems Group](https://systems.ethz.ch/) at ETH Zurich.
       My research interests are at the intersection of data management, machine learning, and systems.

       I received my M.Sc. in Computer Science from Simon Fraser University in 2021, advised by Prof. [Tianzheng Wang](https://www.cs.sfu.ca/~tzwang/), 
       Prof. [Jiannan Wang](https://www.cs.sfu.ca/~jnwang/), and Prof. [Ryan Shea](https://www.sfu.ca/fas/news-and-outreach/years/2019/sfu-mourns-the-loss-of-ryan-shea.html). 
       I received my B.Eng in Software Engineering from Nanjing University in 2018.

#-------------------------------
# Contact links
twitter: https://twitter.com/Yong_jun_He # Add your Twitter handle
linkedin: https://www.linkedin.com/in/yong-jun-he-762485154/
google-scholar: https://scholar.google.com/citations?user=JcXoAVkAAAAJ&hl=en 
mail: yongjun.he@inf.ethz.ch 
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
